export const ActionType = {
    FETCH_PRODUCT_LIST: 'FETCH_PRODUCT_LIST',
    FETCH_PRODUCT_LIST_SUCCESS: 'FETCH_PRODUCT_LIST_SUCCESS',
    FETCH_PRODUCT_LIST_FAILED: 'FETCH_PRODUCT_LIST_FAILED',

    // Cart action
    ADD_PRODUCT_TO_CART: ' ADD_PRODUCT_TO_CART',

    // Filter action
    FILTER_ALL: 'FILTER_ALL',
    FILTER_MEN: 'FILTER_MEN',
    FILTER_WOMEN: 'FILTER_WOMEN',
    FILTER_ACCESSORIES: 'FILTER_ACCESSORIES',
}