export const ActionType = {
    // FETCH_PRODUCT_LIST: 'FETCH_PRODUCT_LIST',
    // FETCH_PRODUCT_LIST_SUCCESS: 'FETCH_PRODUCT_LIST_SUCCESS',
    // FETCH_PRODUCT_LIST_FAILED: 'FETCH_PRODUCT_LIST_FAILED',

    // Cart action
    ADD_PRODUCT_TO_CART: 'ADD_PRODUCT_TO_CART',
    REMOVE_PRODUCT_FROM_CART: 'REMOVE_PRODUCT_FROM_CART',
    DELETE_PRODUCT_FROM_CART: 'DELETE_PRODUCT_FROM_CART',
}